"""Standalone HTML report renderer."""

from __future__ import annotations

import html
import json


_SEVERITY_COLOR = {
    "critical": "#c0392b",
    "high":     "#e67e22",
    "medium":   "#f1c40f",
    "low":      "#27ae60",
    "info":     "#95a5a6",
}

_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f4f6f9; color: #2c3e50; padding: 2rem; }
h1 { font-size: 1.6rem; margin-bottom: 0.3rem; }
.subtitle { color: #7f8c8d; font-size: 0.9rem; margin-bottom: 2rem; }
.cards { display: flex; gap: 1rem; flex-wrap: wrap; margin-bottom: 2rem; }
.card { background: #fff; border-radius: 8px; padding: 1rem 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,.1); min-width: 150px; }
.card .label { font-size: 0.75rem; text-transform: uppercase; color: #7f8c8d; letter-spacing: .05em; }
.card .value { font-size: 2rem; font-weight: 700; }
.severity-pills { display: flex; gap: 0.5rem; flex-wrap: wrap; margin-bottom: 2rem; }
.pill { padding: 0.3rem 0.8rem; border-radius: 999px; color: #fff; font-size: 0.8rem; font-weight: 600; }
table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,.1); }
th { background: #2c3e50; color: #fff; text-align: left; padding: 0.75rem 1rem; font-size: 0.8rem; text-transform: uppercase; letter-spacing: .05em; }
td { padding: 0.7rem 1rem; border-bottom: 1px solid #ecf0f1; font-size: 0.875rem; vertical-align: top; }
tr:last-child td { border-bottom: none; }
tr:hover td { background: #f8f9fa; }
.badge { display: inline-block; padding: 0.2rem 0.6rem; border-radius: 4px; color: #fff; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; }
.mono { font-family: 'SF Mono', 'Fira Code', monospace; font-size: 0.8rem; background: #f1f3f5; padding: 0.1rem 0.4rem; border-radius: 3px; }
.context { color: #7f8c8d; font-size: 0.78rem; }
.ai-note { font-size: 0.78rem; color: #8e44ad; font-style: italic; }
"""


def _badge(severity: str) -> str:
    color = _SEVERITY_COLOR.get(severity, "#95a5a6")
    return f'<span class="badge" style="background:{color}">{html.escape(severity.upper())}</span>'


def render_html(result: dict) -> str:
    summary = result["summary"]
    findings = result["findings"]

    sev_pills = "".join(
        '<span class="pill" style="background:{}">{} {}</span>'.format(
            _SEVERITY_COLOR.get(k, "#95a5a6"), html.escape(k.upper()), v
        )
        for k, v in summary.get("by_severity", {}).items()
    )

    rows = []
    for f in findings:
        location = html.escape(f.get("file", ""))
        if "line" in f:
            location += f":{f['line']}"
        ai = f.get("ai_review") or {}
        ai_cell = ""
        if ai:
            ai_cell = f'<span class="ai-note">{html.escape(ai.get("verdict",""))}' \
                      f'{":" + html.escape(ai["reasoning"]) if ai.get("reasoning") else ""}</span>'
        context = html.escape(f.get("context", ""))
        rows.append(f"""
        <tr>
          <td>{_badge(f['severity'])}</td>
          <td>{html.escape(f['pii_type'])}</td>
          <td><span class="mono">{html.escape(f['value'])}</span></td>
          <td>{f['risk_score']}</td>
          <td>{location}</td>
          <td class="context">{context}</td>
          <td>{ai_cell}</td>
        </tr>""")

    table_body = "".join(rows) if rows else '<tr><td colspan="7" style="text-align:center;color:#7f8c8d;padding:2rem">No findings</td></tr>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PIIWatch Report</title>
  <style>{_CSS}</style>
</head>
<body>
  <h1>PIIWatch Scan Report</h1>
  <p class="subtitle">Generated by PIIWatch</p>

  <div class="cards">
    <div class="card">
      <div class="label">Total Findings</div>
      <div class="value">{summary['total_findings']}</div>
    </div>
    <div class="card">
      <div class="label">Overall Risk Score</div>
      <div class="value">{summary['overall_risk_score']}</div>
    </div>
  </div>

  <div class="severity-pills">{sev_pills}</div>

  <table>
    <thead>
      <tr>
        <th>Severity</th><th>Type</th><th>Value</th><th>Risk</th><th>File</th><th>Context</th><th>AI Review</th>
      </tr>
    </thead>
    <tbody>
      {table_body}
    </tbody>
  </table>

  <script>
    // Embed raw data for anyone who wants to script against the report
    window.PIIWATCH_DATA = {json.dumps(result)};
  </script>
</body>
</html>
"""
